database "s3" {
  json Storage {
    "backet": "user_profiles",
    "filename": "uuid"
  }
  json StorageGuild {
    "backet": "guild_profiles",
    "filename": "uuid"
  }
}


node "goyda-auth-service" {
  [Аутентификация] -> access_jwt
  [Аутентификация] -> refresh_jwt
  http - [Аутентификация]
  oauth -> [Аутентификация]
  refresh_jwt -> [Jwt refresher]
  [Jwt refresher] -> access_jwt
}

database "goyda-auth-storage" {
  folder "goyda-auth-postgres" {
    json Users {
      "username":"covalski",
      "uuid": "42621230-9357-45f9-ad77-9ad93beb1a37",
      "email": "kovalski@goydazvon.com",
      "hash": "c402dd93321356e65d9c4a10590cad9e",
      "auth_provider": "google|bare"
    }
    json Sessions {
      "user_uuid": "42621230-9357-45f9-ad77-9ad93beb1a37",
      "session_name": "mobile",
      "refresh_jwt_uuid": "a49bc641-f3a1-4931-ac2f-7744c1de3a5b"
    }
    [Users] <- [Sessions]
  }
}

[Аутентификация] <-> [Users]
[Jwt refresher] <-> [Sessions]


node "goyda-user-service" {
  аватарка <- [Управление] 
  никнейм <- [Управление]
  дата_регистрации <- [Управление]
  access_jwt --> [Управление]
}

[Storage] <-> [Управление]

database "goyda-user-storage" {
  folder "goyda-user-postgres" {
    json UserData {
      "uuid":"42621230-9357-45f9-ad77-9ad93beb1a37",
      "nickname": "Glavniy pinguin",
      "avatar": "/images/avatar/42621230-9357-45f9-ad77-9ad93beb1a37.png",
      "registration_date": "1751915296"
    }
  }
}

[Управление] <-> [UserData]


node "goyda-guild-service" {
  [Настройка гильдии] <-- access_jwt
  [Настройка гильдии] <-> [Данные гильдии] 
  uuid <- [Данные гильдии] 
  аватарка_гильдии <- [Данные гильдии]
  аватарка_гильдии <-> [StorageGuild]
  название_гильдии <- [Данные гильдии]
  [Участники гильдии] -> [Users]
}

database "goyda-guild-storage" {
  folder "goyda-guild-postgres" {
    json GuildData {
      "uuid": "42621230-9357-45f9-ad77-9ad93beb1a37",
      "creator": "creator_uuid",
      "guild_name": "Охотники на картошку",
      "avatar": "/images/guild/42621230-9357-45f9-ad77-9ad93beb1a37.png",
      "public_url": "potatoman",
      "type": "private|public"
    }
    json GuildUsers {
      "guild_uuid": "42621230-9357-45f9-ad77-9ad93beb1a37",
      "user_uuid": "42621230-9357-45f9-ad77-9ad93beb1a37"
    }
  }
}
[Данные гильдии] <-> [GuildData]
[Участники гильдии] <-> [GuildUsers]
[GuildUsers] -> [Users]
[GuildData] -> [Users]