name: Generate UML Diagrams for README

on:
  push:
    paths:
      - '**.puml'
      - '.github/workflows/uml.yaml'
  workflow_dispatch:

jobs:
  build-uml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz


    - name: Download PlantUML
      run: |
        curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.6/plantuml-1.2024.6.jar

    - name: Generate UML (SVG and PNG)
      run: |
        mkdir -p plantuml_generated
        find diagrams -name "*.puml" -exec java -jar plantuml.jar -tsvg -o ../plantuml_generated {} +
        find diagrams -name "*.puml" -exec java -jar plantuml.jar -tpng -o ../plantuml_generated {} +

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git status
        git add plantuml_generated/*
        git status
        git diff --cached --quiet || git commit -m "Auto-update UML diagrams"
        git push
